version: '2'

services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: ${PROJECT_NAME}_mysql
    restart: always
    ports:
    - ${MYSQL_EXT_PORT}:3306
    volumes:
    - ./db-dump:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}_pma
    links:
    - mysql
    environment:
    - PMA_HOST=mysql
    restart: always
    ports:
    - ${PMA_EXT_PORT}:80

  php:
    container_name: ${PROJECT_NAME}_fpm
    image: zaek/php-fpm
    volumes:
    - "../app/:/home/zaek"
    links:
    - mysql
    - memcached
    - redis

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:latest
    ports:
    - ${NGINX_EXT_PORT}:80
    volumes:
    - "../app/:/home/zaek"
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
    - php

  memcached:
    container_name: ${PROJECT_NAME}_mc
    image: memcached:latest

  redis:
    container_name: ${PROJECT_NAME}_redis
    image: redis:latest
